var id = 0;
            
var itemsDetails = [
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TWO',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 8,
        restrictStock: 15,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'THREE',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 0,
        restrictStock: 15,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'FOUR',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 0,
        restrictStock: 15,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'FIVE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 0,
        restrictStock: 14,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'SIX',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 0,
        restrictStock: 5,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'SEVEN',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 0,
        restrictStock: 5,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'EIGHT',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 5,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'NINE',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 5,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'ONE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 7,
        restrictStock: 16,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TWO',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 8,
        restrictStock: 15,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'THREE',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 0,
        restrictStock: 15,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'FOUR',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 0,
        restrictStock: 15,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'FIVE',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 0,
        restrictStock: 14,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'SIX',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 0,
        restrictStock: 5,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'SEVEN',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 0,
        restrictStock: 5,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'EIGHT',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 5,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'NINE',
        itemDescription: 'Hey Hie',
        uom: 'GALLONS',
        available: 'YES',
        openStock: 5,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    },
    {
        itemCode: id++,
        itemName: 'TEN',
        itemDescription: 'Hey Hie',
        uom: 'FEET',
        available: 'YES',
        openStock: 77,
        restrictStock: 0,
        threshold: 0,
        active: 'YES'
    }
];